FROM python:3.10

WORKDIR /app

RUN apt-get update
RUN pip install --upgrade pip

COPY ./Front ./Front
COPY ./utils ./Front/utils
COPY ./Front/requirements.txt .
COPY .env .

RUN pip install -r requirements.txt

EXPOSE 8510

ENTRYPOINT ["streamlit","run","./Front/main.py"]