FROM python:3.10

WORKDIR /app

RUN apt-get update
RUN pip install --upgrade pip

COPY Front .
COPY utils .

RUN pip install -r requirements.txt

EXPOSE 8501

ENTRYPOINT ["streamlit","run"]
CMD ["main.py"]